---
execution:
  scenario:
    script: testfile.jmx
  concurrency: 5
  ramp-up: 5s
  hold-for: 10m
modules:
  jmeter:
    properties:
      https.default.protocol: TLSv1.2
  blazemeter:
    browser-open: false
    token: 9eb97f4d96003e52d944
  console:
    disable: true
  consolidator:
    generalize-labels: false
reporting:
  - module: blazemeter
    test: demo.yml
  - module: console
  - module: junit-xml
    filename: ./junit.xml
    data-source: pass-fail
  - module: fail-criteria
    criterias:
    - avg-rt>120s for 30s, continue as failed
    - fail>10% for 10s, continue as failed
